### ISSUE TITLE
Did each question/topic has its own id as a permanent link?

### ISSUE THREAD

**Issue by jokeum** [g0v/wiselike#20]
2 ways:
1. wiselike.tw/user/audreyt/123
2. wiselike.tw/qa/123

Which is better?
BTW, the thread.id of the link should be posts.id of discourse, if they are unique?

**Comment by jokeum** [comment]
possible solution:
wiselike.tw/topic_id#post_id
give each topic_id a single page, and go #anchor to post_id
(user_id is optional)

**Comment by jokeum** [comment]
or,
wiselike.tw/word/topic_id#post_id
wiselike.tw/ana/topic_id#post_id
wiselike.tw/say/topic_id#post_id

**Comment by youchenlee** [comment]
or

 - wiselike.tw/wisdom/{topic_id}#{post_id}
 - wiselike.tw/{username}/wisdom/{topic_id}#{post_id}
 - wiselike.tw/{username}/{topic_id}#{post_id}

**Comment by audreyt** [comment]
`https://wiselike.tw/#/user/{username}-{post_id}`
