### ISSUE TITLE
未登入時點選發問，應先引導「註冊」或「登入」 / 或開放匿名發問

### ISSUE THREAD

**Issue by youchenlee** [g0v/wiselike#22]
點發問時時，會出現：
<img width="657" alt="screen shot 2017-05-24 at 15 14 58" src="https://cloud.githubusercontent.com/assets/181350/26391109/eef8016e-4093-11e7-922f-6881ee82efac.png">

如果沒有登入，直接輸入問題，會在點選「確定」後才提示登入：
<img width="662" alt="screen shot 2017-05-24 at 15 15 10" src="https://cloud.githubusercontent.com/assets/181350/26391139/03a26776-4094-11e7-9f03-c358c6877785.png">

解決方法：
1. 未登入時，點「發問」時應該不要跳出「發問」框，而是出現「發問前請先申請帳號、或登入」的說明文件，引導使用者到 discourse 註冊或於 wiselike.tw 登入
2. 或是開放 anonymous 發問。

**Comment by smith02620** [comment]
(2) 已開放anonymous 提問
