### ISSUE TITLE
已登入者不能發問；未登入者不能登入

### ISSUE THREAD

**Issue by kong0107** [g0v/wiselike#33]
發問要送出時會持續處在「處理中」的狀態；而全螢幕的 layer 其實蓋掉了一個「回覆失敗」的錯誤提示。

嘗試清除 cookie 並再次登入時，發現 https://proxy.wiselike.tw/login 會回傳 `502 Bad Gateway` 。

**Comment by kong0107** [comment]
似已修復。

**Comment by kong0107** [comment]
又發生了 @@

測試環境：
* Windows 8.1 64-bit
* Chrome 61

（已清除 wiselike 跟 PDIS 的 Cookie ，亦已於無痕視窗試過，結果相同）

**Comment by jokeum** [comment]
已修復。原因是 server 掛掉，重開之後需手動 run proxy。
