### ISSUE TITLE
Chrome瀏覽器底下，聯絡我們網頁的「寄信過來」按鈕沒有反應

### ISSUE THREAD

**Issue by Avalonalan** [g0v/wiselike#41]

**Comment by Avalonalan** [comment]
【Env】
OS: Windows10
Browser: Chrome 80.0.3987.132 (Official Build) (64-bit)

**Comment by jokeum** [comment]
請問是在那個頁面有「聯絡我們」&「寄信過來」？目前應該沒有這個設計唷。

**Comment by Avalonalan** [comment]
您好,

不好意思晚回復您了。
在早些時候因為急著聯繫您，所以並未注意到wiselike跟PDIS是兩個不同的東西，真是抱歉。
的確如您所說的，在wiselike這邊並無此設計。

我所發現的是
https://pdis.nat.gov.tw/zh-TW/contact/
此網頁內的「寄信過來」。
不管我如何將browser cache clear以及cleear之後重開瀏覽器，按其按鈕皆無反應。
然後在Firefox時候，按下按鈕卻莫名打開Chrome瀏覽器。

在不太適當的地方，舉報這個，深感抱歉。希望您能修復其功能或者告知該負責人。
感謝您。

**Comment by jokeum** [comment]
OK 了解~ 
那個「寄信過來」的動作其實只是打開你的預設 Email 程式寄信而已，猜想可以檢查一下你的裝置設定？
Wiselike 跟 PDIS 兩個確實是不同專案，剛好維護團隊差不多。我們之後會在那邊多增加描述，感謝意見。
