### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by ystartgo** [g0v/wiselike#47]
https://proxy.wiselike.tw/login show 502 Bad Gateway

**Comment by ronnywang** [comment]
前幾個月被加入主機的 root ，就來幫忙解決這問題了 XD

前幾日因為 Linode 安全性更新，造成機器重開
重開後 nginx-naxsi-ui 就跑不起來了（不知道為什麼，而且好像連 nginx-naxsi-ui 都不見了)
所以我重裝 nginx-naxsi-ui 跑起來了

請再確認看看現在是否能使用吧

**Comment by ystartgo** [comment]
不過目前狀態
如何申請帳號？
會無法顯示如圖登入視窗
https://talk.pdis.nat.gov.tw/uploads/default/optimized/1X/5bad300814811f81bb3e91a92c0c9ae786850453_2_600x220.png

**Comment by jokeum** [comment]
應該是 server 端設定的問題，目前正在檢查中~

**Comment by jokeum** [comment]
Done.
