### ISSUE TITLE
Cannot ask question and cannot subcribe

### ISSUE THREAD

**Issue by Amanda-L** [g0v/wiselike#58]
急~當我提交問題時，系統一直顯示無法回覆或未定義。subscribe功能也無法使用。
謝謝。
<img width="226" alt="Screenshot 2021-01-17 200929" src="https://user-images.githubusercontent.com/52643725/104840047-ef528700-58ff-11eb-9354-8d1c215742f5.png">

**Comment by jokeum** [comment]
Hi, 已重開修正~

**Comment by Amanda-L** [comment]
謝謝你! 可以發送了。
